### PR TITLE
Nn translation

### PR DESCRIPTION
**Pull request by dittaeva**

### CODE REVIEW

**Comment by emericg** [comment]
Thanks a lot that's awesome.
Nn is Norwegian right? How do you said Norwegian in Norwegian? to add the language in the settings :)

**Comment by dittaeva** [comment]
Written Norwegian has two varieties, Bokmål and Nynorsk. So this is "Norwegian Nynorsk" in English. In the settings it should be "Norsk (nynorsk)" in Norwegian.

**Comment by emericg** [comment]
Ok thank you, I've finished the setup hopefully.
I didn't check, did you started your translation from an existing file or did you generate a new one from the lupdate command?

What platform are you using to test? There should be new beta release for the 1.0 version this week.

**Comment by dittaeva** [comment]
I generated the translation file (lupdate). The generation made changes to other translations as well, but I didn't include those. I've only used Android until now, but could try on Linux as well.

I also found some things I would like to tweak in the English original. I suppose I should do those changes directly in the code, and let lupdate update watchflower_en.ts?

**Comment by emericg** [comment]
Yes that's good.
The lupdate should be run as infrequently as possible, and if possible during a phase where the source strings don't change (much). Otherwise translation is an ever moving target.

**Pull request merged**
