### PR TITLE
updated NL FY DA translations 

### PR DESCRIPTION
**Pull request by FYr76**
Hope it's done okay.

### CODE REVIEW

**Comment by emericg** [comment]
Yes it's awesome thanks!
There was a couples of problems on the .fy file related to character escaping (with the ' and < >) but other than that it went smoothly. I've published a new beta but I think I'll move it to public release really soon.

**Comment by FYr76** [comment]
Strange indeed, it was the way I copied it from GitHub. Cool, I expect no more changes from my side

**Comment by FYr76** [comment]
This is everything I found.


 
 
```
't Doet
Energy-sensoren
"locatietoestemming"
```




```
Jou grinswearden
```




```
in, zoals
```



```
Dizze
```


 
```
dokumintaasje
```



By the way, I'd like to see a yellow graph line. Any specific reason it isn't there yet?

**Comment by emericg** [comment]
Thanks for the corrections, I've put them on the next version and the 0.13 b2 is now the release.

The my experience with the yellow graph line is that it's usually not great looking. Most value are between 0-1k, but if your plant got direct sun just once in the two weeks the graph is now 0-100k and you can't see much except one spike. But I can give it another try, or at least make it possible to enable/disable it.

**Comment by FYr76** [comment]
You're right, I'll update at irregular times with  different light intensities. So probably it's not so nice. Hopefully you'll  manage to read and plot the memory... maybe that's the moment for the yellow line

**Pull request merged**
