### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by FYr76**
Fun to do this and contribute to your project.

### CODE REVIEW

**Comment by FYr76** [comment]
I found some small errors and changed small things in both languages. Changing it and a new pullrequest?

**Comment by emericg** [comment]
Yes you can just commit new changes and start a new pull request, I think it'll automatically superseed this one.

**Comment by emericg** [comment]
Ok I think you made the new pull requests between two branches of your own repository ^^
I'm pretty sure you just need to accept both of these (on your own repository), then just start a new pull request from the master branch, and then it will appear here!
That should be quick. Also don't worry about separating the two langages that's really not that important.

**Comment by FYr76** [comment]
Okay this way?

**Comment by emericg** [comment]
Awesome thanks!

**Comment by FYr76** [comment]
Avec plaisir

**Pull request merged**
